tianhaoz95/fastlane-plugin-flutter_version

- .github/workflows/sentry.yml
- .gitignore
- .rubocop.yml
- fastlane-plugin-flutter_version.gemspec
- fastlane/Fastfile
- fixture/malformed_version_information/pubspec.yaml
- lib/fastlane/plugin/flutter_version/actions/flutter_version_action.rb
- spec/flutter_version_action_spec.rb
- spec/spec_helper.rb
> dev: fix linting and add codecov

- lib/fastlane/plugin/flutter_version/version.rb
Finally, the tests and the CIs are ready.
> chore: bump version to v1.0.0

- .github/config.yml
- .github/tests_checker.yml
Probably this can make collaboration better, but idk if that's the case. Remove if it's annoying.
> chore: add a few apps

- .github/workflows/auto-approve.yml
This should hopefully save me some time ;)
> chore: auto approve dependabot pr

- .github/workflows/rubocop-analysis.yml
This is not needed since it's already in the Gemfile
> fix: remove excessive deps installation

- lib/fastlane/plugin/flutter_version/actions/flutter_version_action.rb
> chore: remove outdated todo

- lib/fastlane/plugin/flutter_version/version.rb
- spec/flutter_version_action_spec.rb
> chore: bump version to 1.0.1

- README.md
- docs/README.md
> docs: dup some instructions from the GEM site

- .github/workflows/release-drafter.yml
This is needed because ... I'm too busy with the work :(
> feat: auto publish

- .github/release-drafter.yml
> chore: include a few more tags in auto releasing

- docs/README.md
> chore: keep README in sync

- README.md
- docs/README.md
> docs: add details about spec location def

- docs/_sidebar.md
- docs/index.html
- docs/options.md
> docs: add details for options

- README.md
- docs/README.md
> docs: add links to options

- README.md
Using this command works now. 
Dir.chdir "../.." do sh("flutter", "build", "appbundle", "--release") end # Call Flutter Build
> Example updated with do/end for script

- docs/README.md
> fix: sync readme

- .github/workflows/auto-approve.yml
> feat: auto approve all contributor changes

- README.md
> Fix ios build command in README

- docs/README.md
> chore: sync readme to docs

- README.md
> docs: make fastlane section

- .github/workflows/copy-readme.yml
> fix: some issues in copy readme

- .github/workflows/copy-readme.yml
> fix: wrong config filename

- docs/README.md
> [Dup File Action] automated file duplication

- .github/workflows/sentry.yml
- example/variants/no_version_code.yaml
- fastlane/Fastfile
> feat: add end to end test for no version code

- .mergify.yml
> feat: add mergify rule for README sync PRs

- .github/workflows/pr-checks.yml
> fix: remove auto approve conditions

- .github/dependabot.yml
> fix: add auto update for npm

- README.md
> fix: domain has expired

- .github/workflows/auto-approve.yml
- .github/workflows/release.yml
- .github/workflows/rubocop-analysis.yml
Created new token since the previous ones expired
> fix: standardize token usage
